/**
 * Asset storage contract.
 *
 * Every generated byte — voice-over, image, clip, final MP4 — lives on
 * Cloudflare R2 under a key that STARTS with the tenant id. That prefix is the
 * storage half of tenant isolation: a signed URL leaks one object, never a
 * neighbour's folder.
 *
 * The R2 implementation is not written yet. This file exists so that the code
 * needing storage (voice-over today, image and video generation next) is
 * written against a frozen interface instead of waiting — and so that the one
 * rule that must never bend, the tenant prefix, is enforced in a single
 * function rather than at every call site.
 */

export interface AssetStore {
  /** Stores bytes and returns the key they can be read back by. */
  put(key: string, body: Buffer, contentType: string): Promise<string>;
  /** Short-lived URL for reading one object. */
  signedUrl(key: string, expiresInSeconds?: number): Promise<string>;
}

export class StorageNotConfiguredError extends Error {
  readonly statusCode = 503;

  constructor() {
    super(
      'Asset storage is not wired up yet: R2 credentials and lib/storage/r2.ts ' +
        'are missing. Voice-over, image and video generation all depend on it.'
    );
    this.name = 'StorageNotConfiguredError';
  }
}

export class InvalidAssetKeyError extends Error {
  constructor(key: string) {
    super(`Refusing an asset key outside its tenant prefix: ${key}`);
    this.name = 'InvalidAssetKeyError';
  }
}

const SEGMENT = /^[a-zA-Z0-9._-]+$/;
/**
 * `.` and `..` match SEGMENT — the dot is a legitimate character in a filename
 * — so they are excluded by name. Missing this is how `7/../8/secret.mp3`
 * becomes a valid-looking key for tenant 7.
 */
const TRAVERSAL = new Set(['.', '..']);

/**
 * Builds `<tenantId>/<parts…>`, rejecting anything that could climb out of it.
 * Path traversal in an object key is how one tenant reads another's assets.
 */
export function assetKey(tenantId: number, ...parts: string[]): string {
  if (!Number.isInteger(tenantId) || tenantId <= 0) {
    throw new InvalidAssetKeyError(`tenant ${tenantId}`);
  }
  if (parts.length === 0) {
    throw new InvalidAssetKeyError('<empty>');
  }
  for (const part of parts) {
    if (!SEGMENT.test(part) || TRAVERSAL.has(part)) {
      throw new InvalidAssetKeyError(parts.join('/'));
    }
  }
  return [tenantId, ...parts].join('/');
}

/** True when a key belongs to that tenant. Used before signing anything. */
export function keyBelongsToTenant(key: string, tenantId: number): boolean {
  return key.startsWith(`${tenantId}/`) && !key.includes('..');
}

export function createAssetStore(): AssetStore {
  throw new StorageNotConfiguredError();
}
